# This workflow will scrap GitHub trending projects daily.

name: Daily Github Trending

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "*.py"
  schedule:
    - cron: "0 2 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Truncate
      run: |
        current_date=$(date "+%Y-%m-%d")
        ten_days_ago=$(date -d "$current_date - 10 days" "+%Y-%m-%d")
        sed -i "/$ten_days_ago/d" README.md
        
    - name: Run Scraper
      run: |
        python scraper.py
    
    - name: Check for changes
      id: git-status
      run: |
        git diff --exit-code || echo "::set-output name=changed::true"
      continue-on-error: true
    
    # Runs a set of commands using the runners shell
    - name: Push to origin master
      if: steps.git-status.outputs.changed == 'true'
      run: |
        echo start push
        git config --global user.name "$GITHUB_ACTOR"
        git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
        
        git add -A
        git commit -m $(date '+%Y-%m-%d')
        git push

    - name: Delete Workflow Runs
      uses: anaer/delete-workflow-runs@main
      with:
        retain_days: 2
        keep_minimum_runs: 3
        
